name:                HuskNet
version:             0.1.0.0
github:              "Malenczuk/HuskNet"
license:             BSD3
author:              "Maleńczuk Marcin"
maintainer:          ""
copyright:           "2018 Author Maleńczuk Marcin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Feedforward Neural Network
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

description:         Please see the README on Github at <https://github.com/Malenczuk/HuskNet#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- bytestring
- random
- split
- binary
- zlib
- array
- MonadRandom
- gloss
- tasty
- tasty-hunit
- tasty-quickcheck

library:
  source-dirs: src

executables:
  HuskNet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HuskNet

tests:
  HuskNet-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HuskNet
